name: flutter_uis
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.3

environment:
  sdk: '>=2.7.0 <3.0.0'
  # sdk: '>=2.12.0-135.0.dev <3.0.0'

dependency_overrides:
  provider: 5.0.0-nullsafety.1
  intl: 0.17.0-nullsafety.2
  quiver: 3.0.0-nullsafety.2

flutter_icons:
  includes:
    - fea
    - mco
    - ent
    - faw5s

analyzer:
  - enable-experiment:
      - non-nullable

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_core: 0.5.3
  firebase_analytics: 6.3.0
  firebase_performance: 0.4.3
  firebase_crashlytics: 0.2.4

  share: 0.6.5
  hive: 1.4.4+1
  open_url: 1.0.1
  hive_flutter: 0.3.1
  url_launcher: 5.4.1
  universal_io: 1.0.1
  admob_flutter: 1.0.1

  emojis: 0.8.1
  recase: 3.0.0
  faker: 1.3.0
  pigment: 1.0.3
  tinycolor: 1.0.3
  flutter_icons: 1.1.0
  dotted_border: 1.0.6
  fluttery_dart2: 0.0.9
  stretchy_header: 1.0.8
  touchable_opacity: 1.1.2
  page_transition: 1.1.7+2
  percent_indicator: 2.1.1+1
  supercharged: 2.0.0-nullsafety.0
  simple_animations: 3.0.0-nullsafety.2

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  glob: 1.2.0
  path: 1.8.0-nullsafety.3
  translator: 0.1.4
  intl_translation: 0.17.10
  yaml: 2.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/langs/

    - assets/user/
    - assets/food/
    - assets/thumbnails/

    - assets/ma-hfd/
    - assets/ma-skv/
    - assets/ma-hab/
    - assets/ma-asc/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: fonts/Nunito/Nunito-Light.ttf
          weight: 300
        - asset: fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: fonts/Nunito/Nunito-Black.ttf
          weight: 900

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Montserrat/Montserrat-Black.ttf
          weight: 900

    - family: Muli
      fonts:
        - asset: fonts/Muli/Muli-ExtraLight.ttf
          weight: 200
        - asset: fonts/Muli/Muli-Light.ttf
          weight: 300
        - asset: fonts/Muli/Muli-Regular.ttf
          weight: 400
        - asset: fonts/Muli/Muli-SemiBold.ttf
          weight: 600
        - asset: fonts/Muli/Muli-Bold.ttf
          weight: 700
        - asset: fonts/Muli/Muli-ExtraBold.ttf
          weight: 800
        - asset: fonts/Muli/Muli-Black.ttf
          weight: 900

    - family: BebasNeue
      fonts:
        - asset: fonts/BebasNeue/BebasNeue-Regular.ttf
          weight: 400
